import { GoalLog, GoalTemplate, Material, Player, PositionMaster } from "@/lib/types";

export const positionMasters: PositionMaster[] = [
  { id: "op-center", label: "センター", side: "offense" },
  { id: "op-quarterback", label: "QB", side: "offense" },
  { id: "op-runner", label: "ランナー", side: "offense" },
  { id: "op-receiver", label: "レシーバー", side: "offense" },
  { id: "op-flex", label: "フレックス", side: "offense" },
  { id: "dp-rusher", label: "ラッシャー", side: "defense" },
  { id: "dp-linebacker", label: "LB", side: "defense" },
  { id: "dp-cornerback", label: "CB", side: "defense" },
  { id: "dp-safety", label: "セーフティ", side: "defense" },
  { id: "dp-flag-keeper", label: "フラッグキーパー", side: "defense" },
];

export const players: Player[] = [
  {
    id: "p1",
    name: "あおい",
    jerseyNumber: "7",
    gradeLabel: "1ねん",
    active: true,
    guardianName: "佐藤さん",
    favoriteSkill: "はしる",
    offensePositionId: "op-runner",
    defensePositionId: "dp-cornerback",
    offenseGoal: "ボールを最後まで見る",
    defenseGoal: "フラッグを1回ねらう",
  },
  {
    id: "p2",
    name: "はると",
    jerseyNumber: "12",
    gradeLabel: "2ねん",
    active: true,
    guardianName: "田中さん",
    favoriteSkill: "キャッチ",
    offensePositionId: "op-receiver",
    defensePositionId: "dp-safety",
    offenseGoal: "スタートで1歩目を早く出す",
  },
  {
    id: "p3",
    name: "ゆい",
    jerseyNumber: "21",
    gradeLabel: "2ねん",
    active: true,
    guardianName: "山田さん",
    favoriteSkill: "よける",
    offensePositionId: "op-flex",
    defensePositionId: "dp-linebacker",
    defenseGoal: "中のコースを守る",
  },
  {
    id: "p4",
    name: "そうた",
    jerseyNumber: "3",
    gradeLabel: "3ねん",
    active: true,
    guardianName: "井上さん",
    favoriteSkill: "まもる",
    offensePositionId: "op-center",
    defensePositionId: "dp-rusher",
    offenseReflection: "声をかけながらスタートできた",
  },
  {
    id: "p5",
    name: "みお",
    jerseyNumber: "18",
    gradeLabel: "1ねん",
    active: false,
    guardianName: "中村さん",
    favoriteSkill: "こえだし",
    offensePositionId: "op-quarterback",
    defensePositionId: "dp-flag-keeper",
  },
];

export const goalTemplates: GoalTemplate[] = [
  {
    id: "g1",
    side: "offense",
    title: "こえをかける",
    prompt: "短い言葉を差し込んで、今日の声かけ目標にします。",
    emoji: "📣",
    color: "orange",
    templateText: "{input}を3回言う",
    inputPlaceholder: "ナイス",
  },
  {
    id: "g2",
    side: "offense",
    title: "見るポイント",
    prompt: "どこを見るかを入れると、そのまま今日の目標になります。",
    emoji: "👀",
    color: "blue",
    templateText: "{input}を最後まで見る",
    inputPlaceholder: "ボール",
  },
  {
    id: "g3",
    side: "defense",
    title: "すぐ動く",
    prompt: "テンプレートだけで使える、入力なしの目標です。",
    emoji: "💨",
    color: "green",
    templateText: "スタートの合図で1歩目を早く出す",
  },
  {
    id: "g4",
    side: "defense",
    title: "守りをがんばる",
    prompt: "守備で何をするかを差し込めます。",
    emoji: "🏈",
    color: "yellow",
    templateText: "{input}を1回ねらう",
    inputPlaceholder: "はた取り",
  },
];

export const goalLogs: GoalLog[] = [
  {
    id: "l1",
    playerId: "p1",
    goalTemplateId: "g1",
    goalText: "こえを3回出す",
    date: "2026-04-14",
    by: "guardian",
  },
  {
    id: "l2",
    playerId: "p2",
    goalTemplateId: "g2",
    goalText: "ボールを最後まで見る",
    date: "2026-04-14",
    by: "guardian",
  },
  {
    id: "l3",
    playerId: "p4",
    goalTemplateId: "g3",
    goalText: "スタートの合図で1歩目を早く出す",
    date: "2026-04-13",
    note: "コーチがタブレットで補助",
    by: "coach",
  },
];

export const materials: Material[] = [
  {
    id: "m1",
    title: "4月のれんしゅうメニュー",
    description: "Google Slidesで作った今月の練習テーマです。",
    type: "slide",
    audience: "all",
    updatedAt: "2026-04-13",
    url: "https://docs.google.com/presentation/",
  },
  {
    id: "m2",
    title: "試合出欠シート",
    description: "保護者向けの回答用Google Sheetsです。",
    type: "sheet",
    audience: "guardians",
    updatedAt: "2026-04-12",
    url: "https://docs.google.com/spreadsheets/",
  },
  {
    id: "m3",
    title: "コーチ向け指導メモ",
    description: "公開範囲をコーチのみにした資料の例です。",
    type: "doc",
    audience: "coaches",
    updatedAt: "2026-04-10",
    url: "https://docs.google.com/document/",
  },
];
