import { FilmRoomVideo, GoalLog, GoalTemplate, Material, Player, PositionMaster, Season, SeasonGoal } from "@/lib/types";

export const positionMasters: PositionMaster[] = [
  { id: "op-center", label: "センター", side: "offense" },
  { id: "op-quarterback", label: "QB", side: "offense" },
  { id: "op-runner", label: "ランナー", side: "offense" },
  { id: "op-receiver", label: "レシーバー", side: "offense" },
  { id: "op-flex", label: "フレックス", side: "offense" },
  { id: "dp-rusher", label: "ラッシャー", side: "defense" },
  { id: "dp-linebacker", label: "LB", side: "defense" },
  { id: "dp-cornerback", label: "CB", side: "defense" },
  { id: "dp-safety", label: "セーフティ", side: "defense" },
  { id: "dp-flag-keeper", label: "フラッグキーパー", side: "defense" },
];

export const players: Player[] = [
  {
    id: "p1",
    name: "あおい",
    jerseyNumber: "7",
    gradeLabel: "1ねん",
    active: true,
    guardianName: "佐藤さん",
    favoriteSkill: "はしる",
    offensePositionIds: ["op-runner"],
    defensePositionIds: ["dp-cornerback"],
    practiceEntries: [
      {
        practiceDate: "2026-04-18",
        offenseGoal: "ボールを最後まで見る",
        defenseGoal: "フラッグを1回ねらう",
      },
    ],
  },
  {
    id: "p2",
    name: "はると",
    jerseyNumber: "12",
    gradeLabel: "2ねん",
    active: true,
    guardianName: "田中さん",
    favoriteSkill: "キャッチ",
    offensePositionIds: ["op-receiver"],
    defensePositionIds: ["dp-safety"],
    practiceEntries: [
      {
        practiceDate: "2026-04-18",
        offenseGoal: "スタートで1歩目を早く出す",
      },
    ],
  },
  {
    id: "p3",
    name: "ゆい",
    jerseyNumber: "21",
    gradeLabel: "2ねん",
    active: true,
    guardianName: "山田さん",
    favoriteSkill: "よける",
    offensePositionIds: ["op-flex"],
    defensePositionIds: ["dp-linebacker"],
    practiceEntries: [
      {
        practiceDate: "2026-04-18",
        defenseGoal: "中のコースを守る",
      },
    ],
  },
  {
    id: "p4",
    name: "そうた",
    jerseyNumber: "3",
    gradeLabel: "3ねん",
    active: true,
    guardianName: "井上さん",
    favoriteSkill: "まもる",
    offensePositionIds: ["op-center"],
    defensePositionIds: ["dp-rusher"],
    practiceEntries: [
      {
        practiceDate: "2026-04-12",
        offenseGoal: "スナップ前に声を出す",
        offenseReflectionRating: 4,
        offenseReflectionComment: "声をかけながらスタートできた",
      },
    ],
  },
  {
    id: "p5",
    name: "みお",
    jerseyNumber: "18",
    gradeLabel: "1ねん",
    active: false,
    guardianName: "中村さん",
    favoriteSkill: "こえだし",
    offensePositionIds: ["op-quarterback"],
    defensePositionIds: ["dp-flag-keeper"],
    practiceEntries: [],
  },
];

export const goalTemplates: GoalTemplate[] = [
  {
    id: "g1",
    side: "offense",
    title: "こえをかける",
    prompt: "短い言葉を差し込んで、今日の声かけ目標にします。",
    emoji: "📣",
    color: "orange",
    templateText: "{input}を3回言う",
    inputPlaceholder: "ナイス",
  },
  {
    id: "g2",
    side: "offense",
    title: "見るポイント",
    prompt: "どこを見るかを入れると、そのまま今日の目標になります。",
    emoji: "👀",
    color: "blue",
    templateText: "{input}を最後まで見る",
    inputPlaceholder: "ボール",
  },
  {
    id: "g3",
    side: "defense",
    title: "すぐ動く",
    prompt: "テンプレートだけで使える、入力なしの目標です。",
    emoji: "💨",
    color: "green",
    templateText: "スタートの合図で1歩目を早く出す",
  },
  {
    id: "g4",
    side: "defense",
    title: "守りをがんばる",
    prompt: "守備で何をするかを差し込めます。",
    emoji: "🏈",
    color: "yellow",
    templateText: "{input}を1回ねらう",
    inputPlaceholder: "はた取り",
  },
];

export const goalLogs: GoalLog[] = [
  {
    id: "l1",
    playerId: "p1",
    goalTemplateId: "g1",
    goalText: "こえを3回出す",
    date: "2026-04-14",
    by: "guardian",
  },
  {
    id: "l2",
    playerId: "p2",
    goalTemplateId: "g2",
    goalText: "ボールを最後まで見る",
    date: "2026-04-14",
    by: "guardian",
  },
  {
    id: "l3",
    playerId: "p4",
    goalTemplateId: "g3",
    goalText: "スタートの合図で1歩目を早く出す",
    date: "2026-04-13",
    note: "コーチがタブレットで補助",
    by: "coach",
  },
];

export const materials: Material[] = [
  {
    id: "m1",
    title: "4月のれんしゅうメニュー",
    description: "Google Slidesで作った今月の練習テーマです。",
    type: "slide",
    audience: "all",
    updatedAt: "2026-04-13",
    url: "https://docs.google.com/presentation/",
  },
  {
    id: "m2",
    title: "試合出欠シート",
    description: "保護者向けの回答用Google Sheetsです。",
    type: "sheet",
    audience: "guardians",
    updatedAt: "2026-04-12",
    url: "https://docs.google.com/spreadsheets/",
  },
  {
    id: "m3",
    title: "コーチ向け指導メモ",
    description: "公開範囲をコーチのみにした資料の例です。",
    type: "doc",
    audience: "coaches",
    updatedAt: "2026-04-10",
    url: "https://docs.google.com/document/",
  },
];

export const filmRoomVideos: FilmRoomVideo[] = [
  {
    id: "fv1",
    title: "春季大会 vs Blue Falcons",
    description: "限定公開の試合動画。オフェンスの隊形とキャッチ後の動きを見返す用です。",
    sourceLabel: "2026年春季大会 第2試合",
    matchDate: "2026-04-14",
    audience: "all",
    updatedAt: "2026-04-15",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    clips: [
      {
        id: "fc1",
        title: "右サイドのショートパス",
        startSeconds: 42,
        endSeconds: 58,
        down: 1,
        toGoYards: "8",
        formation: "Trips Right",
        playType: "ショートパス",
        playerLinks: [
          { playerId: "p1", positionId: "op-runner" },
          { playerId: "p2", positionId: "op-receiver" },
        ],
        comment: "スナップ後の一歩目が早く、レシーバーの角度もそろっています。",
      },
      {
        id: "fc2",
        title: "中央ランで前進",
        startSeconds: 78,
        endSeconds: 93,
        down: 2,
        toGoYards: "4",
        formation: "Balanced",
        playType: "ラン",
        playerLinks: [{ playerId: "p4", positionId: "op-center" }],
        comment: "センターの声かけからスタートまでが安定しているプレーです。",
      },
      {
        id: "fc3",
        title: "守備でフラッグを取り切る",
        startSeconds: 126,
        endSeconds: 139,
        down: 3,
        toGoYards: "6",
        penaltyType: "なし",
        formation: "Zone",
        playType: "守備",
        playerLinks: [{ playerId: "p3", positionId: "dp-linebacker" }],
        comment: "中のコースを消しながら、最後にしっかり寄せてフラッグを取れています。",
      },
    ],
  },
  {
    id: "fv2",
    title: "プレー合わせメモ",
    description: "限定公開の事前共有動画。プレーの入り方を短く切り出して確認できます。",
    sourceLabel: "プレー合わせ",
    matchDate: "2026-04-16",
    audience: "coaches",
    updatedAt: "2026-04-16",
    youtubeUrl: "https://youtu.be/dQw4w9WgXcQ",
    clips: [
      {
        id: "fc4",
        title: "モーション確認",
        startSeconds: 15,
        endSeconds: 29,
        formation: "Motion Left",
        playType: "プレー合わせ",
        playerLinks: [{ playerId: "p5", positionId: "op-quarterback" }],
        comment: "動き出すタイミングをそろえるための確認用です。",
      },
    ],
  },
];

export const seasons: Season[] = [
  {
    id: "s1",
    label: "2026年春季大会",
    startDate: "2026-03-01",
    targetDate: "2026-05-25",
    active: true,
  },
  {
    id: "s2",
    label: "2025年秋季大会",
    startDate: "2025-09-01",
    targetDate: "2025-11-16",
    active: false,
  },
];

export const seasonGoals: SeasonGoal[] = [
  {
    id: "sg1",
    playerId: "p1",
    seasonId: "s1",
    offenseGoal: "パスキャッチを3回せいこうさせる",
    defenseGoal: "フラッグを毎回ねらう",
    createdAt: "2026-03-08",
    updatedAt: "2026-03-08",
  },
  {
    id: "sg2",
    playerId: "p4",
    seasonId: "s1",
    offenseGoal: "スナップを毎回せいかくにする",
    defenseGoal: "ラッシュで2回QBにプレッシャーをかける",
    offenseReflectionRating: 4,
    offenseReflectionComment: "スナップはほぼ完ぺきだった",
    createdAt: "2026-03-08",
    updatedAt: "2026-04-10",
  },
];
